language: node_js
branches:
  only:
    - main
node_js:
  - stable
npm: true
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: DefwlJp55qkS+kDj90dhO80unnJbpjDdnklZBcD7YZr9NE0tZBxvsdos+bh/uI7G3wYcT+SC5rrDRybb/mVUpItUFQQ7sss1bVYrKPsLAZqCwB5fWU85fg19B3IEE8sANI2K3gsvyiD0mTub2E9ZOF4FsFmbbdeL1PMJFUm1dAEg2iXS5Zr1l36pEaNgSXCPGbY5LIeqKjVCavd1LsRJxMFYtYnmFZuzCEluSEtklHLMdHwt2D68s3sERS/N4uRYZ7ACLFcp6kU33oSMiP072JERMnfZkFhTIiEnilCrtm9wm1m6Ep0+WrgNXYsm2k8BJ68M8f7AwwyOAbf9f4jdD9SSKXIUs7eRH0GehPCwRvb4PQLXRuV8yM0kHmAJmYg3aqKdkH7PIYG3lZzcg176thwmUlz5UdOE4kcWng5DJR5MJABa19ReE8PZQNEvfnILMdQpLIFsvfaYsYLfvA99lDWnKoqJI8VxvUzyrDM5ItK//lk3DssvBUcTejtKsfucNm389IpcugC+YFHxZ7iHrnyaxhuUuH6+qdhDpp7HV3fLRby7sPxrZl7I7SM8bVxUh60nSx+DiAvk+c8s6/kEvtXVBKrLrtP/Px3jn7Fe/XndqmGc8wn0uYlCIUtbmb1jS4BAzRaDY3gIsUj0h5fFAJj6VM6bU9j+S+ppXT65cOg=
  app: tranquil-everglades-14225
  on:
    repo: eapostol/github-travis-heroku
    branch: main
  skip_cleanup: 'true'

