language: node_js
branches:
  only:
  - main
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Ypv8J1NBulEHXrbszphwkWw7M7q4MWkjMeZZ0y5vTyEwLErYp6+VtfnZS8/oghyyPPsevmZcnx9GumqJQb+zS8ooEigo5xFa74Uowhqp7fhvrwujprhRE1vgOc7zUJBpeMsY3Z6QsnKa38pd61p6EKgynoNKobNWR4dwYshVsMq6/XLSEdThjrh8p3jcGh8ahMM38LaJM0eyk9NywWkrY+Y/oQ9/sZYj5eH2S2/TfLN3pEkn6y7K8iLcoF/JKXvKUq/GMCQziJsFwBHJj9JAinI04QCZhzEbeEUV8Bbq8wR2s/mwpG1xiUDdoDCh2K3hjPbr/YNE2RvVNX3gBPhgtAbc28Ij+Ru/83CYn07HYUQgq8+QqMsIjmZYcXDIzWX/i6wFlJfzKfhGKsgcPGBk5XNP3JoK6TZ5i962eJXxLYzvWbOAICoqo5nh7rjLhRMtPi0cPRx87UuNQW5OBqRgBHaOmdYRdGQQSGseAFaKEzQYazh8B8WBU/WsFyHNb86BpcahwExSpfap9PFTEQL+QOLeOgRw1mYKi9tlz2/YYPUQ3ZHBRbj70oq5LQW/c362D1JqKOH0SJLhHN7PQS7c30moNH08sY+iYeXV0izNIDvkufskaATuPpPFCV7VnMt/o297wh2h5EJUzLCPIizwcdQyasj/k1ULykfh9Z0ZKDY=
  app: tranquil-everglades-14225
  on:
    repo: eapostol/github-travis-heroku
    branch: main
  skip_cleanup: 'true'
